kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1alpha1
metadata:
  labels:
    app.kubernetes.io/created-by: rhods-operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: datasciencecluster
    app.kubernetes.io/part-of: rhods-operator
  name: kserve
spec:
  components:
    codeflare:
      enabled: false
    dashboard:
      enabled: false
    datasciencepipelines:
      enabled: false
    kserve:
      enabled: true
    modelmeshserving:
      enabled: false
    ray:
      enabled: false
    workbenches:
      enabled: false
